project: Encodings_Models_for_Multimodal_sweep_fullytrained
entity: tobias-seibel
method: grid
metric:
  goal: maximize
  name: test/c_index
parameters:
  num_workers :
    value :  2
  epochs:
    value: 40
  alpha:
    value: 0.25
  l1_lambda:
    value: 0
  d_gen_out:
    value: 32
  learningrate:
    value: 1e-6
  d_hidden:
    values: [256,128] 
  activation:
    value: SELU
  bins:
    value: 4
  modality:
    values: [Porpoise,PrePorpoise]
  batchsize:
    value: 1
  datapath:
    value: /nodes/bevog/work4/seibel/data
  dropout:
    values: [0.3,0.5]
  storepath:
    value: /work4/seibel/data/results
  csv_path:
    value: /nodes/bevog/work4/seibel/data/tile_encoder_dataframes
  dim_hist_and_feature_path:
    values: [[384,/nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/vit_mae_tiny_I1K_PT_TCGA_BRCA_FT_HIST_GEN_199eps_features/pt_files],[192,/nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/vit_mae_tiny_I1K_PT_TCGA_BRCA_PLUS_I1K_FT_HIST_100eps_features/pt_files],[192,/nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/vit_mae_tiny_I1Kpretrained300eps_TCGA_BRCA_features/pt_files],[2048,/nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/tcga_brca_20x_features/pt_files]]
  repeating:
    values: [1,2,3,4,5,6,7,8,9,10]
  cohort:
   value : brca
command:
  - python3
  - aggregation.py