project: kfold_fullKMtest3
entity: tobias-seibel
method: grid
metric:
  goal: maximize
  name: c_index_max
parameters:
  epochs:
    value: 2
  alpha:
    value: 0.25
  l1_lambda:
    value: 1e-7
  d_gen_out:
    value: 32
  learningrate:
    value: 1e-6
  activation:
    value: SELU
  bins:
    value: 4
  modality:
    values: [Porpoise,PrePorpoise,hist,hist_attention]
  batchsize:
    value: 1
  datapath:
    value: /nodes/bevog/work4/seibel/data
  dropout:
    value: 0.3
  dim_hist_and_feature_path:
    values: [[192,/nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/vit_mae_tiny_I1Kpretrained300eps_TCGA_BRCA_features/pt_files],[2048,/nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/tcga_brca_20x_features/pt_files]]
  cohort:
   value : brca
command:
  - python3
  - kfold_sweep.py