project: Gen_activations
entity: tobias-seibel
method: grid
metric:
  goal: maximize
  name: c_index_max
parameters:
  epochs:
    value: 40
  alpha:
    values: [0.5,0.25]
  l1_lambda:
    value: 1e-7
  d_gen_out:
    value: 32
  learningrate:
    values: [1e-5,1e-6,1e-7]
  activation:
    values: [SELU,GELU,RELU]
  bins:
    value: 32
  modality:
    value: gen
  batchsize:
    values: [64,128,256]
  datapath:
    value: /nodes/bevog/work4/seibel/data
  dropout:
    value: 0.1
  cohort:
   value : brca

command:
  - python3
  - kfold_sweep.py