project: SNN_sweep
entity: tobias-seibel
method: grid
metric:
  goal: maximize
  name: c_index_max
parameters:
  epochs:
    value: 20
  batchsize:
    value: 1
  alpha:
    value: 0.5
  l1_lambda:
    value: 1e-5
  d_gen_out:
    values: [32,64]
  learningrate:
    value: 1e-4
  activation:
    value: SELU
  bins:
    value: 4
  device:
    values: [cuda,cpu]
  dropout:
    value: 0.1
  cohort:
   value : brca
command:
  - python3
  - kfold_sweep.py