project: testkfoldtotraintest
entity: tobias-seibel
method: grid
metric:
  goal: maximize
  name: test/c_index
parameters:
  num_workers :
    value :  1
  epochs:
    value: 40
  alpha:
    value: 0.25
  l1_lambda:
    value: 0
  d_gen_out:
    value: 32
  learningrate:
    value: 1e-6
  d_hidden:
    value: 256 
  activation:
    value: SELU
  bins:
    value: 4
  modality:
    values: [Porpoise,PrePorpoise,hist,hist_gen]
  batchsize:
    value: 1
  datapath:
    value: /nodes/bevog/work4/seibel/data
  dropout:
    value: 0.5
  storepath:
    value: /work4/seibel/data/results
  csv_path:
    value: /nodes/bevog/work4/seibel/data/testkfoldtott
  dim_hist_and_feature_path:
    value: [192,/nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/vit_mae_tiny_I1Kpretrained300eps_TCGA_BRCA_features/pt_files]
  repeating:
    values: [1,2,3,4,5]
  cohort:
   value : brca
command:
  - python3
  - aggregation.py