mode : train
wandb_settings :
        monitoring : true
        entity : tobias-seibel
        project : Feature_Encoder
        name : maetiny_ft100eps_brca_histo
train_settings:
        ffcv : false
        model_name : VitTiny
        save_dir : /home/seibel/maetiny_ft100eps_brca_histo
        max_epochs : 100
        stochastic_weightaveraging : true
        annealing_epochs : 100
        checkpoint_path : 
        do_test : true
        default_root_dir : /home/seibel/maetiny_ft100eps_brca_histo
        max_steps : -1
        monitor_weights_gradients : true
        profiler : #simple
        log_every_n_steps : 100
        tune : false
        model_params : 
                lr : 0.0005
                ckpt_path : /nodes/bevog/work4/seibel/data/mae_tiny_400e.pth.tar
        datamodule :  TileModule
        dataset_params : 
                df_path_train : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_trainsplit.csv
                df_path_test : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_testsplit.csv
                df_path_val : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_valsplit.csv
                tile_df_path : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/DF_TCGA-BRCA-TIILES-NORM.csv
                batch_size : 512
                num_workers : 6
                
                 
        
encode_settings:
        save_path : /nodes/bevog/work4/seibel/data/TCGA-BRCA-DX-features/vit_mae_tiny_I1K_PT_TCGA_BRCA_FT_HIST_100eps_features
        new_ds_name : pt_files
        mycheckpnt : /home/seibel/maetiny_ft100eps_brca_histo/epoch=81-step=148338.ckpt
        encode_gen : false
        ckpt_path : /nodes/bevog/work4/seibel/data/mae_tiny_400e.pth.tar
        model_name : VitTiny
        batch_size : 128
        num_workers : 3
        pin_memory : true
        model_params : 
                lr : 0.01
                nbins : 4
                alpha : 0.1
        df_tile_slide_path : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/DF_TCGA-BRCA-TIILES-NORM.csv
        df_data_paths : [/nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_trainsplit.csv,/nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_testsplit.csv,/nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_valsplit.csv]
        cntd : true


