mode : train
wandb_settings :
        monitoring : true
        entity : tobias-seibel
        project : Feature_Encoder
        name : maetiny_ft100eps_brca_histo
train_settings:
        ffcv : false
        model_name : SupViTSurv
        save_dir : /home/seibel/maetiny_ft100eps_brca_histo_gen
        max_epochs : 100
        stochastic_weightaveraging : true
        annealing_epochs : 110
        checkpoint_path : 
        do_test : true
        default_root_dir : /home/seibel/maetiny_ft100eps_brca_histo_gen
        max_steps : -1
        monitor_weights_gradients : true
        profiler : #simple
        log_every_n_steps : 100
        tune : false
        model_params : 
                lr : 0.0001
                nbins : 4
                alpha : 0.25
                ckpt_path : /nodes/bevog/work4/seibel/data/mae_tiny_400e.pth.tar
        datamodule :  TileModule
        dataset_params : 
                df_path_train : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_trainsplit.csv
                df_path_test : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_testsplit.csv
                df_path_val : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_valsplit.csv
                tile_df_path : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/DF_TCGA-BRCA-TIILES-NORM.csv
                batch_size : 512
                num_workers : 6
                pin_memory : true
                
                 
        
encode_settings:
        save_path : /nodes/bevog/work4/seibel/data/testing_storetileds
        new_ds_name : new_loop_test1
        mycheckpnt : /nodes/bevog/work4/seibel/data/testing/lightning_logs/o8svd1da/checkpoints/epoch=19-step=36180.ckpt
        encode_gen : false
        ckpt_path : /nodes/bevog/work4/seibel/data/mae_tiny_400e.pth.tar
        model_name : SupViTSurv
        model_params : 
                lr : 0.01
                nbins : 4
                alpha : 0.1
        df_tile_slide_path : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/DF_TCGA-BRCA-TIILES-NORM.csv
        df_data_path : /nodes/bevog/work4/seibel/data/tile_encoder_dataframes/tcga_brca__4bins_testsplit.csv
        cntd : true


